"""intial migrations

Revision ID: b3802e235b9c
Revises: 
Create Date: 2023-02-03 16:38:40.211280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3802e235b9c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fantasy_players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('country', sa.String(length=60), nullable=False),
    sa.Column('team', sa.String(length=60), nullable=False),
    sa.Column('type', sa.String(length=60), nullable=False),
    sa.Column('kind', sa.String(length=60), nullable=False),
    sa.Column('points', sa.Float(), nullable=False),
    sa.Column('credits', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('default', sa.Boolean(), nullable=True),
    sa.Column('permissions', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_roles_default'), 'roles', ['default'], unique=False)
    op.create_table('fantasy_teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player1', sa.String(length=128), nullable=True),
    sa.Column('player2', sa.String(length=128), nullable=True),
    sa.Column('player3', sa.String(length=128), nullable=True),
    sa.Column('player4', sa.String(length=128), nullable=True),
    sa.Column('player5', sa.String(length=128), nullable=True),
    sa.Column('player6', sa.String(length=128), nullable=True),
    sa.Column('player7', sa.String(length=128), nullable=True),
    sa.Column('player8', sa.String(length=128), nullable=True),
    sa.Column('player9', sa.String(length=128), nullable=True),
    sa.Column('player10', sa.String(length=128), nullable=True),
    sa.Column('player11', sa.String(length=128), nullable=True),
    sa.Column('credits', sa.Float(), nullable=False),
    sa.Column('points', sa.Float(), nullable=False),
    sa.Column('wicket_keepers', sa.Integer(), nullable=False),
    sa.Column('batsmens', sa.Integer(), nullable=False),
    sa.Column('all_rounders', sa.Integer(), nullable=False),
    sa.Column('bowlers', sa.Integer(), nullable=False),
    sa.Column('home_team_players', sa.Integer(), nullable=False),
    sa.Column('away_team_players', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player1'], ['fantasy_players.name'], ),
    sa.ForeignKeyConstraint(['player10'], ['fantasy_players.name'], ),
    sa.ForeignKeyConstraint(['player11'], ['fantasy_players.name'], ),
    sa.ForeignKeyConstraint(['player2'], ['fantasy_players.name'], ),
    sa.ForeignKeyConstraint(['player3'], ['fantasy_players.name'], ),
    sa.ForeignKeyConstraint(['player4'], ['fantasy_players.name'], ),
    sa.ForeignKeyConstraint(['player5'], ['fantasy_players.name'], ),
    sa.ForeignKeyConstraint(['player6'], ['fantasy_players.name'], ),
    sa.ForeignKeyConstraint(['player7'], ['fantasy_players.name'], ),
    sa.ForeignKeyConstraint(['player8'], ['fantasy_players.name'], ),
    sa.ForeignKeyConstraint(['player9'], ['fantasy_players.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=128), server_default='', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('sign_in_count', sa.Integer(), nullable=False),
    sa.Column('current_sign_in_on', sa.DateTime(), nullable=True),
    sa.Column('current_sign_in_ip', sa.String(length=45), nullable=True),
    sa.Column('last_sign_in_on', sa.DateTime(), nullable=True),
    sa.Column('last_sign_in_ip', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=512), nullable=True),
    sa.Column('type', sa.String(length=128), nullable=False),
    sa.Column('expired', sa.Boolean(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tokens_key'), 'tokens', ['key'], unique=False)
    op.create_index(op.f('ix_tokens_type'), 'tokens', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tokens_type'), table_name='tokens')
    op.drop_index(op.f('ix_tokens_key'), table_name='tokens')
    op.drop_table('tokens')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('fantasy_teams')
    op.drop_index(op.f('ix_roles_default'), table_name='roles')
    op.drop_table('roles')
    op.drop_table('fantasy_players')
    # ### end Alembic commands ###
